name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  Build-Build:
    name: Synthesize
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: []
    env: {}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |-
          yarn
          yarn build
          git diff --exit-code
      - name: Upload cdk.out
        uses: actions/upload-artifact@v2.1.1
        with:
          name: cdk.out
          path: cdk.out
  Assets-FileAsset1:
    name: Publish Assets Assets-FileAsset1
    needs:
      - Build-Build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Download cdk.out
        uses: actions/download-artifact@v2
        with:
          name: cdk.out
          path: cdk.out
      - name: Install
        run: npm install --no-save cdk-assets
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-skip-session-tagging: true
          role-duration-seconds: 1800
      - name: Publish 0e32d3f91503a0c0c16807c03abe9868ee9947c47a30b9b5130993f45f77831e
          (template)
        run: npx cdk-assets --path
          "cdk.out/assembly-US/USBucketStack1256B33F.assets.json" --verbose
          publish
          "0e32d3f91503a0c0c16807c03abe9868ee9947c47a30b9b5130993f45f77831e:585695036304-us-east-1"
  Assets-FileAsset2:
    name: Publish Assets Assets-FileAsset2
    needs:
      - Build-Build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Download cdk.out
        uses: actions/download-artifact@v2
        with:
          name: cdk.out
          path: cdk.out
      - name: Install
        run: npm install --no-save cdk-assets
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-skip-session-tagging: true
          role-duration-seconds: 1800
      - name: "Publish 00f2465b209575c44977ca8ff1c81d86d002849272ede5a8a90ac87dfff1e494
          "
        run: npx cdk-assets --path
          "cdk.out/assembly-US/USBucketStack1256B33F.assets.json" --verbose
          publish
          "00f2465b209575c44977ca8ff1c81d86d002849272ede5a8a90ac87dfff1e494:585695036304-us-east-1"
      - name: "Publish 00f2465b209575c44977ca8ff1c81d86d002849272ede5a8a90ac87dfff1e494
          "
        run: npx cdk-assets --path
          "cdk.out/assembly-EU/EUBucketStack0F6FDF2E.assets.json" --verbose
          publish
          "00f2465b209575c44977ca8ff1c81d86d002849272ede5a8a90ac87dfff1e494:585695036304-eu-west-2"
  Assets-FileAsset3:
    name: Publish Assets Assets-FileAsset3
    needs:
      - Build-Build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Download cdk.out
        uses: actions/download-artifact@v2
        with:
          name: cdk.out
          path: cdk.out
      - name: Install
        run: npm install --no-save cdk-assets
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-skip-session-tagging: true
          role-duration-seconds: 1800
      - name: Publish 2fb920ac036e4f90e42d8280409f51fc41ba75d1b77b8c1faa0d9fc65ef3ca68
          (template)
        run: npx cdk-assets --path
          "cdk.out/assembly-US/USFunctionStackFE5EB3B1.assets.json" --verbose
          publish
          "2fb920ac036e4f90e42d8280409f51fc41ba75d1b77b8c1faa0d9fc65ef3ca68:585695036304-us-east-1"
  Assets-FileAsset4:
    name: Publish Assets Assets-FileAsset4
    needs:
      - Build-Build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Download cdk.out
        uses: actions/download-artifact@v2
        with:
          name: cdk.out
          path: cdk.out
      - name: Install
        run: npm install --no-save cdk-assets
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-skip-session-tagging: true
          role-duration-seconds: 1800
      - name: "Publish 9f0287d50a07bf32d20457428155487d1dcece75d64fe6e470a459e0a68496dc
          "
        run: npx cdk-assets --path
          "cdk.out/assembly-US/USFunctionStackFE5EB3B1.assets.json" --verbose
          publish
          "9f0287d50a07bf32d20457428155487d1dcece75d64fe6e470a459e0a68496dc:585695036304-us-east-1"
      - name: "Publish 9f0287d50a07bf32d20457428155487d1dcece75d64fe6e470a459e0a68496dc
          "
        run: npx cdk-assets --path
          "cdk.out/assembly-EU/EUFunctionStackAAE89C93.assets.json" --verbose
          publish
          "9f0287d50a07bf32d20457428155487d1dcece75d64fe6e470a459e0a68496dc:585695036304-eu-west-2"
  Assets-FileAsset5:
    name: Publish Assets Assets-FileAsset5
    needs:
      - Build-Build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Download cdk.out
        uses: actions/download-artifact@v2
        with:
          name: cdk.out
          path: cdk.out
      - name: Install
        run: npm install --no-save cdk-assets
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-skip-session-tagging: true
          role-duration-seconds: 1800
      - name: Publish 501ab098166f7a7ef104f87651bccd9195fed570eae80a1c5b5cdbf4e830fc58
          (template)
        run: npx cdk-assets --path
          "cdk.out/assembly-EU/EUBucketStack0F6FDF2E.assets.json" --verbose
          publish
          "501ab098166f7a7ef104f87651bccd9195fed570eae80a1c5b5cdbf4e830fc58:585695036304-eu-west-2"
  Assets-FileAsset6:
    name: Publish Assets Assets-FileAsset6
    needs:
      - Build-Build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Download cdk.out
        uses: actions/download-artifact@v2
        with:
          name: cdk.out
          path: cdk.out
      - name: Install
        run: npm install --no-save cdk-assets
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-skip-session-tagging: true
          role-duration-seconds: 1800
      - name: Publish 70559642dcbe8e2773e79f7ef7f3ba28a235e290bee5c6af97479b0fe6de1298
          (template)
        run: npx cdk-assets --path
          "cdk.out/assembly-EU/EUFunctionStackAAE89C93.assets.json" --verbose
          publish
          "70559642dcbe8e2773e79f7ef7f3ba28a235e290bee5c6af97479b0fe6de1298:585695036304-eu-west-2"
  Prod-US-BucketStack-Deploy:
    name: Deploy USBucketStack1256B33F
    permissions:
      contents: none
    needs:
      - Build-Build
      - Assets-FileAsset1
      - Assets-FileAsset2
      - Build-Build
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-skip-session-tagging: true
          role-duration-seconds: 1800
          role-to-assume: arn:aws:iam::585695036304:role/cdk-hnb659fds-deploy-role-585695036304-us-east-1
          role-external-id: Pipeline
      - uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: US-BucketStack
          template: https://cdk-hnb659fds-assets-585695036304-us-east-1.s3.us-east-1.amazonaws.com/0e32d3f91503a0c0c16807c03abe9868ee9947c47a30b9b5130993f45f77831e.json
          no-fail-on-empty-changeset: "1"
          role-arn: arn:aws:iam::585695036304:role/cdk-hnb659fds-cfn-exec-role-585695036304-us-east-1
  Prod-EU-BucketStack-Deploy:
    name: Deploy EUBucketStack0F6FDF2E
    permissions:
      contents: none
    needs:
      - Build-Build
      - Assets-FileAsset5
      - Assets-FileAsset2
      - Build-Build
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          role-skip-session-tagging: true
          role-duration-seconds: 1800
          role-to-assume: arn:aws:iam::585695036304:role/cdk-hnb659fds-deploy-role-585695036304-eu-west-2
          role-external-id: Pipeline
      - uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: EU-BucketStack
          template: https://cdk-hnb659fds-assets-585695036304-eu-west-2.s3.eu-west-2.amazonaws.com/501ab098166f7a7ef104f87651bccd9195fed570eae80a1c5b5cdbf4e830fc58.json
          no-fail-on-empty-changeset: "1"
          role-arn: arn:aws:iam::585695036304:role/cdk-hnb659fds-cfn-exec-role-585695036304-eu-west-2
  Prod-US-FunctionStack-Deploy:
    name: Deploy USFunctionStackFE5EB3B1
    permissions:
      contents: none
    needs:
      - Build-Build
      - Assets-FileAsset3
      - Assets-FileAsset4
      - Prod-US-BucketStack-Deploy
      - Build-Build
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-skip-session-tagging: true
          role-duration-seconds: 1800
          role-to-assume: arn:aws:iam::585695036304:role/cdk-hnb659fds-deploy-role-585695036304-us-east-1
          role-external-id: Pipeline
      - uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: US-FunctionStack
          template: https://cdk-hnb659fds-assets-585695036304-us-east-1.s3.us-east-1.amazonaws.com/2fb920ac036e4f90e42d8280409f51fc41ba75d1b77b8c1faa0d9fc65ef3ca68.json
          no-fail-on-empty-changeset: "1"
          role-arn: arn:aws:iam::585695036304:role/cdk-hnb659fds-cfn-exec-role-585695036304-us-east-1
  Prod-EU-FunctionStack-Deploy:
    name: Deploy EUFunctionStackAAE89C93
    permissions:
      contents: none
    needs:
      - Build-Build
      - Assets-FileAsset6
      - Assets-FileAsset4
      - Prod-EU-BucketStack-Deploy
      - Build-Build
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          role-skip-session-tagging: true
          role-duration-seconds: 1800
          role-to-assume: arn:aws:iam::585695036304:role/cdk-hnb659fds-deploy-role-585695036304-eu-west-2
          role-external-id: Pipeline
      - uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: EU-FunctionStack
          template: https://cdk-hnb659fds-assets-585695036304-eu-west-2.s3.eu-west-2.amazonaws.com/70559642dcbe8e2773e79f7ef7f3ba28a235e290bee5c6af97479b0fe6de1298.json
          no-fail-on-empty-changeset: "1"
          role-arn: arn:aws:iam::585695036304:role/cdk-hnb659fds-cfn-exec-role-585695036304-eu-west-2
